stages: [validate, plan, apply]

image:
  name: hashicorp/terraform:1.10.5
  entrypoint: [""]

variables:
  TF_ROOT: "${CI_PROJECT_DIR}/Task2Advanced/envs/${ENV}"
  AWS_ACCESS_KEY_ID: "${YC_S3_ACCESS_KEY_ID}"        # из protected/masked variables
  AWS_SECRET_ACCESS_KEY: "${YC_S3_SECRET_ACCESS_KEY}"

before_script:
  - echo "$YC_SA_KEY" > /tmp/sa-key.json
  - export YC_SERVICE_ACCOUNT_KEY_FILE=/tmp/sa-key.json
  - cd "$TF_ROOT"
  - terraform init -input=false

validate:
  stage: validate
  script:
    - terraform fmt -check -recursive
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -input=false -var-file=${ENV}.tfvars -out=tfplan
  artifacts:
    paths: ["${TF_ROOT}/tfplan"]
    expire_in: 1 day

apply:
  stage: apply
  when: manual            # <-- кнопка approval в GitLab
  environment:
    name: ${ENV}
  script:
    - terraform apply -input=false tfplan